# Site settings
title: HypoPG
email: contact@dalibo.com
description: "HypoPG is an extension adding support for hypothetical indexes in PostgreSQL."
twitter_username: ___powa___
github_username:  dalibo
ga_id: UA-637331-8

# Build settings
markdown: kramdown
permalink: pretty
